In [2]:
import pandas as pd 
import numpy as np 

data = pd.read_csv('./UFC.csv')

In [12]:
data.head()

,event_id,event_name,date,location,fight_id,division,title_fight,method,finish_round,match_time_sec,...,b_splm,b_str_acc,b_sapm,b_str_def,b_td_avg,b_td_avg_acc,b_td_def,b_sub_avg,winner,winner_id
0,6e380a4d73ab4f0e,UFC Fight Night: Imavov vs. Borralho,2025/09/06,"Paris, Ile-de-France, France",d14fea43712707f0,lightweight,0,Submission,2,176,...,3.84,57,4.16,60,0.00,0,84,0.0,Benoit Saint Denis,c2299ec916bc7c56
1,6e380a4d73ab4f0e,UFC Fight Night: Imavov vs. Borralho,2025/09/06,"Paris, Ile-de-France, France",5bcd8abf6da01dae,middleweight,0,Decision - Unanimous,5,300,...,3.44,56,2.50,60,1.28,48,76,0.4,Nassourdine Imavov,881bf86d4cba8578
2,6e380a4d73ab4f0e,UFC Fight Night: Imavov vs. Borralho,2025/09/06,"Paris, Ile-de-France, France",0149e875b31e57f8,light heavyweight,0,KO/TKO,1,300,...,2.50,45,3.04,43,1.43,18,35,1.3,Modestas Bukauskas,476fe566d2df676e
3,6e380a4d73ab4f0e,UFC Fight Night: Imavov vs. Borralho,2025/09/06,"Paris, Ile-de-France, France",69b31593175f77ec,lightweight,0,KO/TKO,2,198,...,5.71,41,4.47,50,4.17,55,81,0.2,Mason Jones,f6ad6a1e4d600e0d
4,6e380a4d73ab4f0e,UFC Fight Night: Imavov vs. Borralho,2025/09/06,"Paris, Ile-de-France, France",a47123ae6e048f11,welterweight,0,KO/TKO,3,122,...,4.71,40,7.15,47,0.00,0,47,0.0,Axel Sola,1d2d98ddd05b38fb

In [18]:
print(data.shape)

(8337, 124)

In [36]:
list(data.select_dtypes(include='object').columns)

['event_id',
 'event_name',
 'date',
 'location',
 'fight_id',
 'division',
 'method',
 'referee',
 'r_name',
 'r_id',
 'r_nick_name',
 'r_stance',
 'r_dob',
 'b_name',
 'b_id',
 'b_nick_name',
 'b_stance',
 'b_dob',
 'winner',
 'winner_id']

In [38]:
data.select_dtypes(include='object').head()

,event_id,event_name,date,location,fight_id,division,method,referee,r_name,r_id,r_nick_name,r_stance,r_dob,b_name,b_id,b_nick_name,b_stance,b_dob,winner,winner_id
0,6e380a4d73ab4f0e,UFC Fight Night: Imavov vs. Borralho,2025/09/06,"Paris, Ile-de-France, France",d14fea43712707f0,lightweight,Submission,Herb Dean,Benoit Saint Denis,c2299ec916bc7c56,God of War,Southpaw,1995/12/18,Mauricio Ruffy,9c393e836a852f30,NaN,Orthodox,1996/06/17,Benoit Saint Denis,c2299ec916bc7c56
1,6e380a4d73ab4f0e,UFC Fight Night: Imavov vs. Borralho,2025/09/06,"Paris, Ile-de-France, France",5bcd8abf6da01dae,middleweight,Decision - Unanimous,Marc Goddard,Nassourdine Imavov,881bf86d4cba8578,The Sniper,Orthodox,1996/03/01,Caio Borralho,4126a78111c0855a,The Natural,Southpaw,1993/01/16,Nassourdine Imavov,881bf86d4cba8578
2,6e380a4d73ab4f0e,UFC Fight Night: Imavov vs. Borralho,2025/09/06,"Paris, Ile-de-France, France",0149e875b31e57f8,light heavyweight,KO/TKO,Marc Goddard,Modestas Bukauskas,476fe566d2df676e,The Baltic Gladiator,Switch,1994/02/10,Paul Craig,eabf206b162b3b83,Bearjew,Orthodox,1987/11/27,Modestas Bukauskas,476fe566d2df676e
3,6e380a4d73ab4f0e,UFC Fight Night: Imavov vs. Borralho,2025/09/06,"Paris, Ile-de-France, France",69b31593175f77ec,lightweight,KO/TKO,Rich Mitchell,Bolaji Oki,4bdedbdeedff7d1d,The Zulu Warrior,Orthodox,1995/11/15,Mason Jones,f6ad6a1e4d600e0d,The Dragon,Orthodox,1995/04/26,Mason Jones,f6ad6a1e4d600e0d
4,6e380a4d73ab4f0e,UFC Fight Night: Imavov vs. Borralho,2025/09/06,"Paris, Ile-de-France, France",a47123ae6e048f11,welterweight,KO/TKO,Herb Dean,Axel Sola,1d2d98ddd05b38fb,NaN,Southpaw,1997/09/17,Rhys McKee,f748267c4ab6c127,Skeletor,Orthodox,1995/09/10,Axel Sola,1d2d98ddd05b38fb